### ISSUE TITLE
wrong devices section

### ISSUE THREAD

**Issue by rudibelt** [rick00001/Smartmeter2#2]
I has to use Smartmeterdevice2 as device to get things working:

{
  "id": "Smartmeter2",
  "class": "Smartmeterdevice2",
  "name": "Smartmeter2",
  "serialport": "/dev/ttyUSB0",
  "baudRate" : 9600,
  "dataBits" : 7,
  "parity" : "even",
  "stopBits" : 1,
  "flowControl" : true
}

**Comment by rick00001** [comment]
Thanks, i changed the help readme file
